# Generated by Django 5.1.3 on 2024-11-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('code', models.AutoField(max_length=6, primary_key=True, serialize=False, verbose_name='codigo')),
                ('nombre_usuario', models.CharField(max_length=10, verbose_name='nombreUsuario')),
                ('nombre_completo', models.CharField(max_length=10, verbose_name='nombreCompleto')),
                ('contrasenna', models.CharField(max_length=10, verbose_name='contrasenna')),
                ('tipo_usuario', models.CharField(max_length=10, verbose_name='tipoUsuario')),
            ],
        ),
    ]
