# Generated by Django 5.1.3 on 2024-11-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='codigo'),
        ),
    ]
