# Generated by Django 5.1.3 on 2024-11-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_usuario_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenna',
            field=models.CharField(max_length=20, verbose_name='contrasenna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(max_length=50, verbose_name='nombreCompleto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=20, verbose_name='nombreUsuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(max_length=20, verbose_name='tipoUsuario'),
        ),
    ]
