# Generated by Django 5.1.3 on 2024-11-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_usuario_contrasenna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasenna',
            field=models.CharField(max_length=20, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(max_length=50, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=20, verbose_name='Nombre Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(max_length=20, verbose_name='Tipo Usuario'),
        ),
    ]
