# Generated by Django 5.1.3 on 2024-11-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_usuario_contrasenna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default=12345669, max_length=12),
            preserve_default=False,
        ),
    ]
