# Generated by Django 5.0.6 on 2024-11-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
