# Generated by Django 5.0.6 on 2024-11-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('medico', 'Médico'), ('paciente', 'Paciente'), ('administrador', 'Administrador'), ('cajera', 'Cajera'), ('secretaria', 'Secretaria')], max_length=20, verbose_name='Tipo Usuario'),
        ),
    ]
