# Generated by Django 5.0.6 on 2024-11-21 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_usuario_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('centro1', 'Centro Médico 1'), ('centro2', 'Centro Médico 2'), ('centro3', 'Centro Médico 3')], max_length=50, verbose_name='Centro Médico')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad_medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(choices=[('Jesus S', 'Jesus S')], max_length=50, verbose_name='Médico')),
                ('especialidad', models.CharField(choices=[('cardiologia', 'Cardiología'), ('pediatria', 'Pediatría'), ('dermatologia', 'Dermatología')], max_length=50, verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Especialidad del Médico',
                'verbose_name_plural': 'Especialidades de los Médicos',
            },
        ),
        migrations.CreateModel(
            name='ReservarCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(choices=[('Jesus S', 'Jesus S')], max_length=50, verbose_name='Médico')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('especialidad', models.CharField(choices=[('cardiologia', 'Cardiología'), ('pediatria', 'Pediatría'), ('dermatologia', 'Dermatología')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('centro_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.centromedico', verbose_name='Centro Médico')),
            ],
        ),
    ]
