# Generated by Django 5.0.6 on 2024-11-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_especialidadmedico_delete_especialidad_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centromedico',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Centro Médico'),
        ),
    ]
